version: '3.8'

services:
  clienteservice:
    image: gabrieldataengineer/clienteservice:latest
    ports:
      - "8081:8080"
    dns:
      - 8.8.8.8
    networks:
      - app-network

  estoqueservice:
    image: gabrieldataengineer/estoqueservice:latest
    ports:
      - "8082:8080"
    dns:
      - 8.8.8.8
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - clienteservice
    networks:
      - app-network

  pedidoservice:
    image: gabrieldataengineer/pedidoservice:latest
    ports:
      - "8083:8080"
    dns:
      - 8.8.8.8
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - clienteservice
      - estoqueservice
    networks:
      - app-network

  produtoservice:
    image: gabrieldataengineer/produtoservice:latest
    ports:
      - "8084:8080"
    dns:
      - 8.8.8.8
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - clienteservice
    networks:
      - app-network

  pedidoreceiver:
    image: gabrieldataengineer/pedidoreceiver:latest
    ports:
      - "8085:8080"
    environment:
      - spring.data.mongodb.uri=mongodb+srv://gabrieln91:09090991hgh3099@cluster0.h2pf5c3.mongodb.net/techchallengefase4microservico?retryWrites=true&w=majority
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672
      - spring.rabbitmq.username=guest
      - spring.rabbitmq.password=guest
    depends_on:
      - rabbitmq
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
