version: '3.8'

services:
  clienteservice:
    image: gabrieldataengineer/clienteservice:latest
    ports:
      - "8081:8080"
    dns:
      - 8.8.8.8
    networks:
      - app-network

  estoqueservice:
    image: gabrieldataengineer/estoqueservice:latest
    ports:
      - "8082:8080"
    dns:
      - 8.8.8.8
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - clienteservice
    networks:
      - app-network

  pedidoservice:
    image: gabrieldataengineer/pedidoservice:latest
    ports:
      - "8083:8080"
    dns:
      - 8.8.8.8
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - clienteservice
      - estoqueservice
    networks:
      - app-network

  produtoservice:
    image: gabrieldataengineer/produtoservice:latest
    ports:
      - "8084:8080"
    dns:
      - 8.8.8.8
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - clienteservice
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
